[dev]
  command = "npm run dev"
  framework = "astro"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/"

# Remove the SPA redirect that's causing 404s
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Special redirect for clearing HSTS - users can visit this to clear their cache
[[redirects]]
  from = "/clear-hsts"
  to = "/redirect-instructions.html"
  status = 200
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains", Clear-Site-Data = '"cache", "cookies", "storage"'}

# Additional HSTS clearing path with HTTP support
[[redirects]]
  from = "http://qdaria.com/clear-hsts"
  to = "https://qdaria.com/redirect-instructions.html"
  status = 302
  force = true
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains"}

# Force HTTPS redirect to ensure SSL certificate is used
[[redirects]]
  from = "http://qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Redirect www to non-www to avoid certificate mismatch
[[redirects]]
  from = "https://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Add a fallback for 404 pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
