[dev]
  command = "npm run dev"
  framework = "astro"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/"

# Remove the SPA redirect that's causing 404s
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Add a fallback for 404 pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
