[dev]
  command = "npm run dev"
  framework = "astro"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/"

# Remove the SPA redirect that's causing 404s
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Chrome-specific fix page for SSL issues
[[redirects]]
  from = "/fix"
  to = "/chrome-fix.html"
  status = 200

# Special redirect for clearing HSTS - users can visit this to clear their cache
[[redirects]]
  from = "/clear-hsts"
  to = "/redirect-instructions.html"
  status = 200
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains", Clear-Site-Data = '"cache", "cookies", "storage"'}

# Additional HSTS clearing path with HTTP support
[[redirects]]
  from = "http://qdaria.com/clear-hsts"
  to = "https://qdaria.com/redirect-instructions.html"
  status = 302
  force = true
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains"}

# EMERGENCY BYPASS ROUTES - Multiple fallback options for users with access issues

# Emergency access page with aggressive cache clearing
[[redirects]]
  from = "/emergency"
  to = "/emergency-access.html"
  status = 200
  headers = {Cache-Control = "no-cache, no-store, must-revalidate", Pragma = "no-cache", Expires = "0"}

# Direct bypass to Netlify subdomain
[[redirects]]
  from = "/bypass"
  to = "https://qdaria.netlify.app/"
  status = 302
  force = true
  headers = {Cache-Control = "no-cache, no-store, must-revalidate"}

# Working site redirect
[[redirects]]
  from = "/working"
  to = "https://qdaria.netlify.app/"
  status = 302
  force = true
  headers = {Cache-Control = "no-cache, no-store, must-revalidate"}

# Alternative access points
[[redirects]]
  from = "/access"
  to = "https://qdaria.netlify.app/"
  status = 302
  force = true

[[redirects]]
  from = "/site"
  to = "https://qdaria.netlify.app/"
  status = 302
  force = true

# DNS bypass instructions
[[redirects]]
  from = "/dns-help"
  to = "/dns-bypass-instructions.html"
  status = 200

# Clear all site data and redirect
[[redirects]]
  from = "/reset"
  to = "https://qdaria.netlify.app/"
  status = 302
  force = true
  headers = {Clear-Site-Data = '"cache", "cookies", "storage", "executionContexts"', Cache-Control = "no-cache, no-store, must-revalidate"}

# Force HTTPS redirect to ensure SSL certificate is used
[[redirects]]
  from = "http://qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Redirect www to non-www to avoid certificate mismatch
[[redirects]]
  from = "https://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Add a fallback for 404 pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
