[dev]
  command = "npm run dev"
  framework = "astro"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions/"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Remove the SPA redirect that's causing 404s
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Special redirect for clearing HSTS - users can visit this to clear their cache
[[redirects]]
  from = "/clear-hsts"
  to = "/redirect-instructions.html"
  status = 200
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains", Clear-Site-Data = '"cache", "cookies", "storage"'}

# Additional HSTS clearing path with HTTP support
[[redirects]]
  from = "http://qdaria.com/clear-hsts"
  to = "https://qdaria.com/redirect-instructions.html"
  status = 302
  force = true
  headers = {Strict-Transport-Security = "max-age=0; includeSubDomains"}

# Force HTTPS redirect to ensure SSL certificate is used
[[redirects]]
  from = "http://qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Redirect www to non-www to avoid certificate mismatch
[[redirects]]
  from = "https://www.qdaria.com/*"
  to = "https://qdaria.com/:splat"
  status = 301
  force = true

# Performance optimizations
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Performance thresholds
    performance = 90
    accessibility = 100
    best-practices = 95
    seo = 95

[[plugins]]
  package = "netlify-plugin-cache"

[[plugins]]
  package = "netlify-plugin-image-optim"

# Add a fallback for 404 pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Performance and Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # Performance Headers
    Content-Encoding = "gzip, br"
    Vary = "Accept-Encoding"

# Cache static assets aggressively
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Accept-CH = "DPR, Width, Viewport-Width"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# HTML pages - cache but revalidate
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Link = "</fonts/inter.woff2>; rel=preload; as=font; type=font/woff2; crossorigin=anonymous"
